In [1]:
import numpy as np

In [2]:
print('hello World')

hello World


In [4]:
import sklearn

In [5]:
i= 5

In [6]:
print(7)

7


In [7]:
myarray = np.array([1,2,3,4,5])

In [8]:
myarray

array([1, 2, 3, 4, 5])

In [10]:
myarray = np.array([1,2,3,4,5],np.int8)

In [11]:
myarray

array([1, 2, 3, 4, 5], dtype=int8)

In [12]:
myarray[0]

1

In [14]:
myarray.shape

(5,)

In [15]:
myarray[4] = 10

In [16]:
myarray

array([ 1,  2,  3,  4, 10], dtype=int8)

In [18]:
listArray = np.array([[1,2,3],[5,6,9],[5,8,6]])

In [19]:
listArray

array([[1, 2, 3],
       [5, 6, 9],
       [5, 8, 6]])

In [20]:
listArray.dtype

dtype('int32')

In [21]:
listArray.size

9

In [22]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [24]:
zeros = np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
range = np.arange(15)

In [27]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
emp = np.empty((4,6))

In [30]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.33511018e-306, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [1.33512241e-306, 8.34423068e-308, 8.34426464e-308,
        1.78021527e-306, 9.79107193e-307, 7.56599807e-307],
       [1.42420345e-306, 6.89807188e-307, 1.20160711e-306,
        1.69119330e-306, 1.78022206e-306, 1.78005909e-306]])